# Generated by Django 4.1.3 on 2022-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default="", max_length=450),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
