# Generated by Django 4.1.3 on 2022-11-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_task_description_alter_task_title_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
